// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoReviewDecisionSource } from "./AutoReviewDecisionSource";
import type { GuardianApprovalReview } from "./GuardianApprovalReview";
import type { GuardianApprovalReviewAction } from "./GuardianApprovalReviewAction";

/**
 * [UNSTABLE] Persisted approval auto-review item reconstructed from rollout
 * events. This preserves reviewer-unavailable provenance across resume/read.
 */
export type GuardianApprovalReviewItem = {
/**
 * Stable identifier for this review lifecycle.
 */
id: string,
/**
 * Identifier for the reviewed item or tool call when one exists.
 */
targetItemId: string | null,
/**
 * Unix timestamp (in milliseconds) when this review started.
 */
startedAtMs: number,
/**
 * Unix timestamp (in milliseconds) when this review completed.
 */
completedAtMs: number | null,
/**
 * Source that produced the terminal decision; absent while in progress.
 */
decisionSource: AutoReviewDecisionSource | null, review: GuardianApprovalReview, action: GuardianApprovalReviewAction, };
